/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : MotorsDirection.c
**     Project     : Pathfinder
**     Processor   : MKL46Z256VLL4
**     Component   : 74HC595
**     Version     : Component 01.022, Driver 01.00, CPU db: 3.00.000
**     Repository  : My Components
**     Compiler    : GNU C Compiler
**     Date/Time   : 2016-12-10, 12:54, # CodeGen: 64
**     Abstract    :
**
Driver for the 74HC595 8bit serial shift register.
**     Settings    :
**          Component name                                 : MotorsDirection
**          Latch (STCP)                                   : STCP
**          Data (DS)                                      : DS
**          Clock (SHCP)                                   : SHCP
**          Clock/Latch delay (ns)                         : 19
**          Wait                                           : WAIT1
**          MSB first                                      : no
**          Enable Pin (OE)                                : Enabled
**            Enable in Init                               : yes
**            Enable (OE)                                  : OE
**     Contents    :
**         Enable    - void MotorsDirection_Enable(void);
**         Disable   - void MotorsDirection_Disable(void);
**         ShiftByte - void MotorsDirection_ShiftByte(byte val);
**         Latch     - void MotorsDirection_Latch(void);
**         ReadByte  - byte MotorsDirection_ReadByte(void);
**         WriteByte - void MotorsDirection_WriteByte(byte val);
**         Deinit    - void MotorsDirection_Deinit(void);
**         Init      - void MotorsDirection_Init(void);
**
**     License   :  Open Source (LGPL)
**     Copyright : (c) Copyright Erich Styger, 2013, all rights reserved.
**     Web: http://mcuoneclipse.com
**     This an open source software implementing a driver using Processor Expert.
**     This is a free software and is opened for education, research and commercial developments under license policy of following terms:
**     * This is a free software and there is NO WARRANTY.
**     * No restriction on use. You can use, modify and redistribute it for personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
**     * Redistributions of source code must retain the above copyright notice.
** ###################################################################*/
/*!
** @file MotorsDirection.c
** @version 01.00
** @brief
**
Driver for the 74HC595 8bit serial shift register.
*/         
/*!
**  @addtogroup MotorsDirection_module MotorsDirection module documentation
**  @{
*/         

/* MODULE MotorsDirection. */

#include "MotorsDirection.h"

#define MotorsDirection_STCP_LATCH_DELAY_NS  19 /* delay in nano seconds */
#define MotorsDirection_SHCP_CLOCK_DELAY_NS  19 /* delay in nano seconds */

static uint8_t MotorsDirection_regVal8; /* cached value of the shift register */

#define MotorsDirection_SHIFT_MSB_FIRST  0  /* LSB is shifted first */
/*
** ===================================================================
**     Method      :  MotorsDirection_Latch (component 74HC595)
**     Description :
**         Sends a latch pulse to move the bits from the internal
**         memory to the output pins.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void MotorsDirection_Latch(void)
{
  /* send a latch pulse to show the data on the output pins */
  STCP1_SetVal(); /* set latch to high */
#if MotorsDirection_STCP_LATCH_DELAY_NS != 0
  WAIT1_Waitns(MotorsDirection_STCP_LATCH_DELAY_NS); /* wait according to data sheet */
#endif
  STCP1_ClrVal(); /* set latch to low */
#if MotorsDirection_STCP_LATCH_DELAY_NS != 0
  WAIT1_Waitns(MotorsDirection_STCP_LATCH_DELAY_NS); /* wait according to data sheet */
#endif
}

/*
** ===================================================================
**     Method      :  MotorsDirection_ShiftByte (component 74HC595)
**     Description :
**         Shift a byte to the shift register. The most significant bit
**         will be on output pin 0. Use Latch() to show the data on the
**         output pins.
**     Parameters  :
**         NAME            - DESCRIPTION
**         val             - 8bit value to be shifted
**     Returns     : Nothing
** ===================================================================
*/
void MotorsDirection_ShiftByte(byte val)
{
  uint8_t i;

  /* precondition: latch pin, data pin and clock pin are all low */
  MotorsDirection_regVal8 = val;
  for(i=0;i<8;i++) { /* shift all the 8 bits */
    /* put data bit */
#if MotorsDirection_SHIFT_MSB_FIRST
    if (val&0x80) { /* LSB bit first */
#else /* LSB first */
    if (val&1) { /* LSB bit first */
#endif
      DS1_SetVal();
    } else {
      DS1_ClrVal();
    }
#if MotorsDirection_SHCP_CLOCK_DELAY_NS != 0
    WAIT1_Waitns(MotorsDirection_SHCP_CLOCK_DELAY_NS); /* wait according to data sheet */
#endif
    SHCP1_SetVal(); /* CLK high: data gets transfered into memory */
#if MotorsDirection_SHCP_CLOCK_DELAY_NS != 0
    WAIT1_Waitns(MotorsDirection_SHCP_CLOCK_DELAY_NS); /* wait according to data sheet */
#endif
    DS1_ClrVal(); /* data line low */
#if MotorsDirection_SHCP_CLOCK_DELAY_NS != 0
    WAIT1_Waitns(MotorsDirection_SHCP_CLOCK_DELAY_NS); /* wait according to data sheet */
#endif
    SHCP1_ClrVal(); /* CLK high: data gets transfered into memory */
#if MotorsDirection_SHIFT_MSB_FIRST
    val <<= 1; /* next bit */
#else
    val >>= 1; /* next bit */
#endif
  }
}

/*
** ===================================================================
**     Method      :  MotorsDirection_Enable (component 74HC595)
**     Description :
**         Enables the device
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void MotorsDirection_Enable(void)
{
  OE1_ClrVal(); /* device enabled */
}

/*
** ===================================================================
**     Method      :  MotorsDirection_Disable (component 74HC595)
**     Description :
**         Disables the device
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void MotorsDirection_Disable(void)
{
  OE1_SetVal(); /* device disabled */
}

/*
** ===================================================================
**     Method      :  MotorsDirection_Deinit (component 74HC595)
**     Description :
**         Deinitializes the driver
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void MotorsDirection_Deinit(void)
{
  /* nothing needed here */
}

/*
** ===================================================================
**     Method      :  MotorsDirection_Init (component 74HC595)
**     Description :
**         Initializes the driver
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void MotorsDirection_Init(void)
{
  MotorsDirection_regVal8 = 0;
  STCP1_ClrVal(); /* latch */
  DS1_ClrVal(); /* data */
  SHCP1_ClrVal(); /* clock */
  MotorsDirection_Enable(); /* enable device */
}

/*
** ===================================================================
**     Method      :  MotorsDirection_WriteByte (component 74HC595)
**     Description :
**         Shifts the given byte and latches it.
**     Parameters  :
**         NAME            - DESCRIPTION
**         val             - value to be shifted into the shift
**                           register. The value will be latched and
**                           will appear on the output pins.
**     Returns     : Nothing
** ===================================================================
*/
void MotorsDirection_WriteByte(byte val)
{
  MotorsDirection_ShiftByte(val); /* shift byte to the shift register */
  MotorsDirection_Latch(); /* latch it and show it on the output pins */
}

/*
** ===================================================================
**     Method      :  MotorsDirection_ReadByte (component 74HC595)
**     Description :
**         Returns the current value of the shift register. The current
**         value of the shift register is cached in the driver.
**     Parameters  : None
**     Returns     :
**         ---             - current shift register value (cached)
** ===================================================================
*/
byte MotorsDirection_ReadByte(void)
{
  return MotorsDirection_regVal8;
}

/* END MotorsDirection. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
